include("test-override.jl")
using Pkg

analyzePkg(pkg :: String) = (Pkg.add(pkg); Pkg.test(pkg))

analyzePkg("Printf")
analyzePkg("Revise")
analyzePkg("Flux")
analyzePkg("IJulia")
analyzePkg("Gadfly")
analyzePkg("Gen")
analyzePkg("DifferentialEquations")
analyzePkg("JuMP")
analyzePkg("Knet")
analyzePkg("Plots")
analyzePkg("Genie")
analyzePkg("Turing")
analyzePkg("PyCall")
analyzePkg("DataFrames")
analyzePkg("Zygote")
analyzePkg("TensorFlow")
analyzePkg("MLJ")
analyzePkg("UnicodePlots")
analyzePkg("PackageCompiler")
analyzePkg("Makie")
analyzePkg("Cxx")
