include("test-override.jl")
using Pkg

fd = open("C:/Users/gelin/Documents/computer-science/research/julia/juliette-wa/src/analysis/output.json"; truncate=true)
close(fd)
Pkg.add("Flux")
Pkg.test("Flux")
Pkg.add("IJulia")
Pkg.test("IJulia")
Pkg.add("Gadfly")
Pkg.test("Gadfly")
Pkg.add("Gen")
Pkg.test("Gen")
# Pkg.add("Printf")
# Pkg.test("Printf")
# Pkg.add("Revise")
# Pkg.test("Revise")
